main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('omage/', include('omage.urls')),
    path('admin/', admin.site.urls),
]

omage/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'omage'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('novo_card/', views.cadastrar_card, name='cadastrar_card'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

omage/models.py
from django.db import models

# Create your models here.
class Card(models.Model):
    texto = models.CharField(max_length=250, null=True)
    assinatura = models.CharField(max_length=250)    
    pub_date = models.DateTimeField('data de publicacao')
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.assinatura

omage/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Card
from django.views import generic
from django.utils import timezone
from django.urls import reverse

from .models import Card

# Create your views here.
# def index(request):
#     cards_list = Card.objects.all()
#     context = {'cards_list':cards_list}
#     return render(request, 'omage/index.html', context)

class IndexView(generic.ListView):
    template_name = 'omage/index.html'
    context_object_name = 'cards_list'
    def get_queryset(self):
        return Card.objects.all()

def cadastrar_card(request):
    if request.method == 'GET':
        return render(request, 'omage/new_card.html')
    if request.method == 'POST':
        texto_card = request.POST['texto_card']
        assinatura = request.POST['assinatura']
        img_card = request.FILES.get('img_card')
        pub_data = timezone.now()
        novo_card = Card(texto=texto_card, assinatura=assinatura, pub_date=pub_data, image=img_card)
        novo_card.save()
        lista_cards = Card.objects.all()
        context = {'cards_list': lista_cards}
        return HttpResponseRedirect(reverse('omage:index')) #render(request, 'omage/index.html', context)
        

omage/templates/omage/index.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Omage App</title>
  </head>
  <body>
    
    <h1 style="text-align: center; color: rgb(211, 238, 229);">Bem vindo ao Mural:</h1>
    
<!--     
       
        
       
            <div class="card" >
                <img class="card-img-top" src="{% static card.image %}" alt="Card image cap">
                <div class="card-body">
                
                  <h5 class="card-title">Por {{ card.assinatura }}:</h5>
                  <p class="card-text">{{ card.texto }}</p>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">Publicado em: {{ card.pub_date }}</li>
                </ul>
                <div class="card-body">
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div> -->

        {% if cards_list %}
            <div class="card-group">
              {% for card in cards_list %}
              <div class="card" id="gradient-border">
                <img class="card-img-top" src="{% static card.image %}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{ card.texto }}</h5>
                  <p class="card-text">Por: {{ card.assinatura }}</p>
                </div>
                <div class="card-footer" >
                  <small class="text-muted" style="height: 15px;">Publicado em: {{ card.pub_date }}</small>
                </div>
              </div>
            </div>
       
              {% endfor %}
   
    {% else %}
    <p>Nenhum card ainda cadastrado.</p>
    {% endif %}

    <hr>

    <h3><a href="{% url 'omage:cadastrar_card' %}">Clique aqui para cadastrar um card</a> </h3>


    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

omage/templates/omage/new_card.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Omage App</title>
  </head>
  <body>
    
    <h1 style="text-align: center; color: rgb(211, 238, 229);">Crie o seu cartão abaixo:</h1>

    <form action="{% url 'omage:cadastrar_card' %}" method="post" enctype="multipart/form-data" id="form_cadastro">
        {% csrf_token %}
        <div class="form-group">
            <label for="assinaturaCard" style="color: rgb(211, 238, 229);">Insira seu nome:</label>
            <input type="text" class="form-control" placeholder="Seu nome aqui" name="assinatura">
            <br>
            <label for="textoCard" style="color: rgb(211, 238, 229);">Digite o texto do seu cartão:</label>
            <textarea class="form-control" id="texto_card_id" rows="3" placeholder="Insira o texto do seu cartão aqui" name="texto_card"></textarea>
            <br>
            <label for="uploadimg" style="color: rgb(211, 238, 229);">Insira uma imagem no seu cartão:</label>
            <input type="file" class="form-control-file" id="up_img_file" name="img_card" style="color: rgb(211, 238, 229);">
            <br>
            <button type="submit" class="btn btn-success mb-2">Salvar cartão</button>
        </div>
    </form>
    



    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>